export enum Club {
  'Kohshinjo68',
  'Justice',
  'CleanNClearing',
  'BookClub',
  'Countermeasure',
  'Engineer',
  'FoodService',
  'Fuuki',
  'GourmetClub',
  'HoukagoDessert',
  'KnightsHospitaller',
  'MatsuriOffice',
  'Meihuayuan',
  'Onmyobu',
  'RemedialClass',
  'SPTF',
  'Shugyobu',
  'Endanbou',
  'TheSeminar',
  'TrainingClub',
  'TrinityVigilance',
  'Veritas',
  'NinpoKenkyubu',
  'GameDev',
  'RedwinterSecretary',
  'anzenkyoku',
  'SisterHood',
  'Class227',
  'Emergentology',
  'RabbitPlatoon',
  'PandemoniumSociety',
  'AriusSqud',
  'HotSpringsDepartment',
  'TeaParty',
  'PublicPeaceBureau',
  'BlackTortoisePromenade',
  'Genryumon',
  'LaborParty',
  'EmptyClub',
}
export enum School {
  'Abydos',
  'Arius',
  'Gehenna',
  'Hyakkiyako',
  'Millennium',
  'RedWinter',
  'Shanhaijing',
  'SRT',
  'Trinity',
  'Valkyrie',
  'ETC',
}
export enum TacticRole {
  'DamageDealer',
  'Tanker',
  'Healer',
  'Supporter',
  'Vehicle',
}
export enum BulletType {
  'Explosion',
  'Pierce',
  'Mystic',
  'Normal',
  'Sonic',
}
export enum ArmorType {
  'LightArmor',
  'HeavyArmor',
  'Unarmed',
  'ElasticArmor',
  'Normal',
}

export interface AutoattackSkill {
  SkillType: 'autoattack',
  Effects: {
    Type: string,
    Hits: number[],
    Scale: number[],
    Frames: {
      AttackEnterDuration: number,
      AttackStartDuration: number,
      AttackEndDuration: number,
      AttackBurstRoundOverDelay: number,
      AttackIngDuration: number,
      AttackReloadDuration: number
    },
    CriticalCheck: 'Check'
  }
}
export interface CommonSkill {
  SkillType: 'ex'|'normal'|'gearnormal',
  Name: string,
  Desc: string,
  Parameters: string[][],
  Cost: number[],
  Icon: string,
  Effects: {
    Type: 'DMGSingle'|'BuffSelf',
    CriticalCheck: "Check",
    Scale: number[]
  }[]
}
export interface Student {
    Id: number,
    IsReleased: boolean[],
    DefaultOrder: number,
    PathName: string,
    DevName: string,
    Name: string,
    School: School,
    Club: Club,
    StarGrade: 1|2|3,
    SquadType: 'Main'|'Support',
    TacticRole: TacticRole,
    Summons: [],
    Position: 'Front'|'Middle'|'Back',
    BulletType: BulletType,
    ArmorType: ArmorType,
    StreetBattleAdaptation: number,
    OutdoorBattleAdaptation: number,
    IndoorBattleAdaptation: number,
    WeaponType: string,
    WeaponImg: string,
    Cover: boolean,
    Equipment: [
        Hat,
        Hairpin,
        Watch
    ],
    CollectionBG: string,
    CollectionTexture: string,
    FamilyName: string,
    FamilyNameRuby: null|string,
    PersonalName: string,
    SchoolYear: string,
    CharacterAge: string,
    Birthday: string,
    CharacterSSRNew: string,
    ProfileIntroduction: string,
    Hobby: string,
    CharacterVoice: string,
    BirthDay: string,
    Illustrator: string,
    Designer: string,
    CharHeightMetric: string,
    CharHeightImperial: string,
    StabilityPoint: number,
    AttackPower1: number,
    AttackPower100: number,
    MaxHP1: number,
    MaxHP100: number,
    DefensePower1: number,
    DefensePower100: number,
    HealPower1: number,
    HealPower100: number,
    DodgePoint: number,
    AccuracyPoint: number,
    CriticalPoint: number,
    CriticalDamageRate: number,
    AmmoCount: number,
    AmmoCost: number,
    Range: number,
    RegenCost: number,
    Skills: Array<AutoattackSkill|CommonSkill>,
    FavorStatType: string[],
    FavorStatValue: number[][],
    FavorAlts: number[],
    MemoryLobby: number[],
    MemoryLobbyBGM: string,
    FurnitureInteraction: string[][],
    FavorItemTags: string[],
    FavorItemUniqueTags: string[],
    IsLimited: number,
    Weapon: {
        Name: string,
        Desc: string,
        AdaptationType: string,
        AdaptationValue: number,
        AttackPower1: number,
        AttackPower100: number,
        MaxHP1: number,
        MaxHP100: number,
        HealPower1: number,
        HealPower100: number,
        StatLevelUpType: string
    },
    Gear: {
        Released: boolean[],
        StatType: string[],
        StatValue: number[][],
        Name: string,
        Desc: string,
        Icon: string,
        TierUpMaterial: number[][],
        TierUpMaterialAmount: number[][]
    },
    SkillExMaterial: number[][],
    SkillExMaterialAmount: number[][],
    SkillMaterial: number[][],
    SkillMaterialAmount: number[][]
}